Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\Program Files\Python39\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\Program Files\Python39\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "D:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Program Files\Python39\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "D:\Program Files\Python39\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\Program Files\Python39\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
origin_dir = 'original/'
resized_dir = 'resized/'
gray_dir = 'gray/'

print('number of files in "original" folder:', len(os.listdir(origin_dir)))
print('number of files in "resized" folder:', len(os.listdir(resized_dir)))
print('number of files in "gray" folder:', len(os.listdir(gray_dir)))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[5], line 5[0m
[0;32m      2[0m resized_dir [38;5;241m=[39m [38;5;124m'[39m[38;5;124mresized/[39m[38;5;124m'[39m
[0;32m      3[0m gray_dir [38;5;241m=[39m [38;5;124m'[39m[38;5;124mgray/[39m[38;5;124m'[39m
[1;32m----> 5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mnumber of files in [39m[38;5;124m"[39m[38;5;124moriginal[39m[38;5;124m"[39m[38;5;124m folder:[39m[38;5;124m'[39m, [38;5;28mlen[39m([43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43morigin_dir[49m[43m)[49m))
[0;32m      6[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mnumber of files in [39m[38;5;124m"[39m[38;5;124mresized[39m[38;5;124m"[39m[38;5;124m folder:[39m[38;5;124m'[39m, [38;5;28mlen[39m(os[38;5;241m.[39mlistdir(resized_dir)))
[0;32m      7[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mnumber of files in [39m[38;5;124m"[39m[38;5;124mgray[39m[38;5;124m"[39m[38;5;124m folder:[39m[38;5;124m'[39m, [38;5;28mlen[39m(os[38;5;241m.[39mlistdir(gray_dir)))

[1;31mFileNotFoundError[0m: [WinError 3] 系统找不到指定的路径。: 'original/'

